### ISSUE TITLE
SQLITE_CONSTRAINT error

### ISSUE THREAD

**Issue by TheCrazyInsanity** [VeryBigSad/unnamedBot#13]
logs

Starting up Database stuff...
Trying to log in...
Database ready to work!
Event binding done!
node:events:368
      throw er; // Unhandled 'error' event
      ^

[Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: user_data.user
Emitted 'error' event on Statement instance at:
] {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}

idk what else to say

**Comment by VeryBigSad** [comment]
hm
could your bot encounter differently capitalized but otherwise same usernames on one server?

**Comment by VeryBigSad** [comment]
try to download new version, delete old database file and start the bot up again
