### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Voilee** [VeryBigSad/unnamedBot#14]
Keep getting this message 
Usage: node bot.js [-flag1, -flag2] <host> <port> [<name>] [<password>]

**Comment by Voilee** [comment]
nvm i did it but know i got npm install error

**Comment by Voilee** [comment]
> Keep getting this message Usage: node bot.js [-flag1, -flag2] [] []

So this works but know i got this 

![image](https://user-images.githubusercontent.com/101022078/156933106-3dba6242-66c3-40f6-965d-068ee1dc2f58.png)

**Comment by VeryBigSad** [comment]
are you sure you did `npm install` when in the project directory?

**Comment by VeryBigSad** [comment]
yeah, if you could please
because im confused

**Comment by Voilee** [comment]
> yeah, if you could please because im confused

Ok now im confused you updated the repo yesterday now i get this error 

![image](https://user-images.githubusercontent.com/101022078/157259663-259bb58e-683b-4caf-9272-f97937d07cb1.png)

**Comment by VeryBigSad** [comment]
sent you a request on discord, add me there; VeryBigSad#1987

**Comment by rolkoztm** [comment]
your discord dont work inv me @VeryBigSad

**Comment by VeryBigSad** [comment]
> your discord dont work inv me @VeryBigSad

if you want to contribute you can open a pull request

**Comment by VeryBigSad** [comment]
same thing as #15
