### ISSUE TITLE
Loads of errors when running npm install

### ISSUE THREAD

**Issue by AdomLuk** [VeryBigSad/unnamedBot#15]
Hello, I'm currently having issues when running npm install, does anyone have an idea on how to fix this? Screenshots are provided.

![1](https://user-images.githubusercontent.com/66871969/161825778-9dca310f-e349-43d5-9812-ffb3a2e91277.PNG)
![image](https://user-images.githubusercontent.com/66871969/161825856-a297268f-ace5-45e0-8996-f5cf56e57f0e.png)

**Comment by AdomLuk** [comment]
Ok, I got it to work but I can't make it run if I put my minecraft password.
When I do the command with just the username it works but if I then do the password it'll show up as: 
node bot.js [-flag1, -flag2] <host> <port> [<name>] [<password>]
I've double checked that everything is correct but it still comes up with the issue

**Comment by AdomLuk** [comment]
node bot.js -flag1, -flag2 host port name password*

**Comment by VeryBigSad** [comment]
It might be an issue with the argument reader, never really bug checked it.
Those are the first few lines (1-20) of `index.js` , shouldn't be hard to fix, but might take some time since I'm quite busy at the moment. If you want, feel free to open up a PR.
