### ISSUE TITLE
New Minecraft Auth System

### ISSUE THREAD

**Issue by 4U6V** [VeryBigSad/unnamedBot#5]
So I Was Testing The Bot. I Got Everything To Work However, Since I Am Using A Migrated Account For It, I Am Unable To Log The Account Into A Server. Is There Any Fix For This?

**Comment by iAmInActions** [comment]
Try to sign in with the user name instead of the email. classic (username) accounts usually don't work with email login even after being migrated to mojang. Otherwise you might want to create a new mojang account for the bot.

**Comment by VeryBigSad** [comment]
hey! The problem is that you have to specify to mineflayer that you are using a microsoft account when logging in with one.
All you have to do is in options variable in bot.js add `auth: 'microsoft'`. I will add this as a flag you can use when starting from console later (-microsoft or something).

**Comment by VeryBigSad** [comment]
Okay, I pushed the commit, now you can use it with -microsoft.

**Comment by iAmInActions** [comment]
I thought you mean an old username account that got migrated to mojang and not a microsoft account. my bad.
