### ISSUE TITLE
Switch mysql for sqlite for speed and portability?

### ISSUE THREAD

**Issue by iAmInActions** [VeryBigSad/unnamedBot#6]
Hello, I was just wondering if you could replace mysql with sqlite so the bot can access the database faster. ik that it would be quite some work but it would make the bot more portable, easy to install and more stable. Its up to your decision if you do it but i just wanted to ask so I know if I need to fork and mod it myself or if mysql will become mainline in the near future. It would be pretty dumb if we both started to implement it at the same time. If you actually want to switch, I could help you by making pull requests.

**Comment by VeryBigSad** [comment]
Hey! sqlite is a great idea, mysql was only really used because I didn't know how to implement much else.
I am still not that great in nodejs, so if you could do that - it would be much appreciated.

**Comment by VeryBigSad** [comment]
Currently working on the second version which would use SQLite3.
