### ISSUE TITLE
Add !pp command

### ISSUE THREAD

**Issue by iAmInActions** [VeryBigSad/unnamedBot#8]
This should be an easy add, I made it on my local branch once but it was a bit messy because im not that good at node.
Basically what it does is it prints an ascii string that starts with `8`, then has a random amount of `=` symbols between 2 and 9 and then ends with a `D`.

**Comment by VeryBigSad** [comment]
i'll make sure to add that

**Comment by VeryBigSad** [comment]
done in branch v2; hopefully will be merged into master soon.
